spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=GymManagement;encrypt=true;trustServerCertificate=true

spring.datasource.username=sa
spring.datasource.password=1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=duckgymsecretkeyduckgymsecretkey123456
jwt.expiration=86400000

#spring.datasource.url=jdbc:sqlserver://localhost\\SQLEXPRESS:1433;databaseName=GymManagement;encrypt=true;trustServerCertificate=true
#spring.datasource.username=sa
#spring.datasource.password=123
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#jwt.secret=duckgymsecretkeyduckgymsecretkey123456
#jwt.expiration=86400000
